meta_product_name: "Meetingspace"
meta_title: "Meetingspace - Find offices anywhere and everywhere"
meta_description: "MeetingSpace connects landlords with vacant office space to professionals looking for space to work. MeetingSpace offers unrivalled choice across the globe from 1 person hot desk to 100 people conference rooms."
meta_image: "msfblogo.jpg" # should exist in `app/assets/images/`
twitter_account: "@meetingspace_twitter_account"   # required for Twitter Cards
